DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

USE exampledb;

CREATE TABLE Examples
(
	id int NOT NULL AUTO_INCREMENT,
	ingredientName varchar(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE Recipes
(
	id int NOT NULL AUTO_INCREMENT,
	recipeName varchar(255) NOT NULL,
    photo varchar(255) NOT NULL,
    recipeNumber int NOT NULL,
    createdAt TIMESTAMP NOT NULL default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

SELECT * FROM Recipes;

SELECT * FROM Examples;
